export default {
  init: false,
  _kind: 'submit',
  kind: [Getter / Setter],
  message: [],
  tag: false,
  gitInfo: {
    alias: 'origin',
    url: '',
    branch: '',
    localBranch: 'test',
    commit: '',
    force: false,
    tags: [],
    tag: '',
    untrackedFiles: [],
    trackedChangedFiles: [
      'CHANGELOG.md',
      'package.json',
      'pnpm-lock.yaml',
      'src/pull/before-merge.ts',
      'src/utils.ts',
      'todo.md',
      '',
    ],
    stashed: false,
    tagged: false,
    committed: true,
    isRoot: true,
  },
  commandParameters: {
    alias: '',
    branch: '',
    init: false,
    force: false,
    tag: false,
    message: [],
    kind: 'submit',
  },
  pkg: { version: '', path: '' },
  voluntaryWIthdrawal: false,
};
